# Generated by Django 4.0.3 on 2022-03-12 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipality',
            old_name='distric',
            new_name='district',
        ),
    ]
