# Generated by Django 4.0.3 on 2022-03-12 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_rename_distric_municipality_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ward',
            old_name='number',
            new_name='ward_number',
        ),
    ]
